### ISSUE TITLE
Add version 5.1

### ISSUE THREAD

**Issue by MementoRC** [conda-forge/cbor2-feedstock#6]
### Comment:

Hi,
Is it possible to add version 5.1? Another recipe has v5.1 in its requirements
possibly this may help
https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions

**Comment by thewchan** [comment]
Should be resolved by https://github.com/conda-forge/cbor2-feedstock/pull/7

**Comment by MementoRC** [comment]
Great!
